#!/usr/bin/env bash

set -e

git clone -b v0.11.1 https://github.com/neovim/neovim.git $HOME/personal/neovim

sudo dnf -y install ninja-build cmake gcc make gettext curl glibc-gconv-extra ripgrep fzf

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

