exec-once = uwsm app -- kitty
windowrule = workspace 1, match:class kitty

exec-once = uwsm app -- firefox
windowrule = workspace 2, match:class firefox

exec-once = uwsm app -- Telegram
windowrule = workspace 3, match:class org.telegram.desktop

exec-once = uwsm app -- spotify
windowrule = workspace 5, match:class spotify

exec-once = uwsm app -- bitwarden-desktop
windowrule = workspace 6, match:class Bitwarden
unbind = SUPER, P
bind = SUPER, P, workspace, 6

exec-once = omarchy-launch-webapp "https://app.hey.com"
windowrule = workspace 7, match:class chrome-app.hey.com__-Default
bind = SUPER, E, workspace, 7

exec-once = omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
windowrule = workspace 8, match:class chrome-app.hey.com__calendar_weeks_-Default
bind = SUPER, H, workspace, 8

exec-once = omarchy-launch-webapp "https://chatgpt.com"
windowrule = workspace 19, match:class chrome-chatgpt.com__-Default
bind = SUPER, C, workspace, 19

exec-once = uwsm app -- kitty
windowrule = workspace 1, match:class kitty

exec-once = uwsm app -- firefox
windowrule = workspace 2, match:class firefox

exec-once = uwsm app -- Telegram
windowrule = workspace 3, match:class org.telegram.desktop

exec-once = uwsm app -- spotify
windowrule = workspace 5, match:class spotify

exec-once = uwsm app -- bitwarden-desktop
windowrule = workspace 6, match:class Bitwarden
unbind = SUPER, P
bind = SUPER, P, workspace, 6

exec-once = omarchy-launch-webapp "https://app.hey.com"
windowrule = workspace 7, match:class chrome-app.hey.com__-Default
bind = SUPER, E, workspace, 7

exec-once = omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
windowrule = workspace 8, match:class chrome-app.hey.com__calendar_weeks_-Default
bind = SUPER, H, workspace, 8

exec-once = omarchy-launch-webapp "https://chatgpt.com"
windowrule = workspace 19, match:class chrome-chatgpt.com__-Default
bind = SUPER, C, workspace, 19

