# Numbers

exec-once = uwsm app -- kitty
windowrule = workspace 1, match:class kitty

exec-once = uwsm app -- firefox
windowrule = workspace 2, match:class firefox

exec-once = uwsm app -- Telegram
windowrule = workspace 3, match:class org.telegram.desktop

exec-once = uwsm app -- chromium
windowrule = workspace 4, match:class chromium

exec-once = uwsm app -- spotify
windowrule = workspace 5, match:class Spotify

# Letters

exec-once = uwsm app -- bitwarden-desktop
windowrule = workspace 11, match:class Bitwarden
unbind = SUPER, P
bind = SUPER, P, workspace, 11

exec-once = omarchy-launch-webapp "https://app.hey.com"
windowrule = workspace 12, match:class chrome-app.hey.com__-Default
bind = SUPER, E, workspace, 12

exec-once = omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
windowrule = workspace 13, match:class chrome-app.hey.com__calendar_weeks_-Default
bind = SUPER, H, workspace, 13

exec-once = omarchy-launch-webapp "https://claude.ai"
windowrule = workspace 14, match:class chrome-claude.ai__-Default
bind = SUPER, C, workspace, 14

exec-once = uwsm app -- steam
windowrule = workspace 15, match:class steam
bind = SUPER, S, workspace, 15

exec-once = omarchy-launch-webapp "https://discord.com/channels/@me"
windowrule = workspace 16, match:class chrome-discord.com__channels_@me-Default
bind = SUPER, D, workspace, 16

# Reserved for games
bind = SUPER, A, workspace, 17
unbind = SUPER, SHIFT, A
bind = SUPER SHIFT, A, movetoworkspace, 17
